events {}

http {
    server {
        listen 80;

        # Serve dashboard (static files)
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }

        # Processing service
        location /api/processing/ {
            proxy_pass http://processing-service:8080/;
        }

        # Analyzer service
        location /api/analyzer/ {
            proxy_pass http://analyzer-service:8080/;
        }

        # Health check service
        location /api/health/ {
            proxy_pass http://health-check-service:8120/;
        }
    }
}